#!/usr/bin/php
<?php

/**
 * Drupal Module Builder
 * 
 * Simple command line package to help create the base of a new module
 * 
 * @author Josh Waihi (http://geek.joshwaihi.com/)
 */

define('CORE', '6.x');
define('API_LIB', '/var/lib/drupal-module-builder/apis');

/**
 * Help
 */
function help() {
  $file = basename(__FILE__);
  echo "
  Drupal Module Builder
  
  $file helps create quick drupal module skeletons to save you a lot
  of typing. It creates .info, .install and .module files inside a 
  folder that you sepcify the location of. $file allows you to specify
  which hooks you want to use and provides tab completetion for them.
  
  Usage: 
    $file --core [CORE]
      - Create a module for version [CORE] of Drupal (numeric: 5,6 or 7). Defaults to 6
    $file --help
      - Show this help message
  Parameters:
    --core      which major version of core the hooks apply too.
    --api-lib   define an alternative api lib to read hooks from.

";
  die;
}

/**
 * Parse the arguments passed to the script
 */
function args($key) {
  static $args;
  if ($args != NULL) {
    return $args[$key];
  }
  $args = array();
  
  // Get rid of the first argument, its the script name.
  array_shift($_SERVER['argv']);
  while ($param = array_shift($_SERVER['argv'])) {
    if (strpos($param, '--') !== FALSE) {
      $param = str_replace('--', '', $param);
      $args[$param] = array_shift($_SERVER['argv']);
      if ($param == 'help') {
        $args[$param] = TRUE;
      }
    }
  }
  return isset($args[$key]) ? $args[$key] : FALSE;
}

/**
 * Wrapper function for asking questions to the user.
 * 
 * The idea is to later add support so libreadline is not required.
 */
function ask_question($question) {
  return readline($question);
}

/**
 * Ask a required question the the user.
 */
function require_answer($question) {
  $value = ask_question($question);
  if (empty($value)) {
    echo "This is a required value. Please answer provide a value.\n";
    return require_answer($question);
  }
  return $value;
}

/**
 * Get a list of supported hooks
 */
function get_hooks() {
  static $hooks = array();
  if (!empty($hooks)) {
    return $hooks;
  }
  if (!$core = (int) args('core')) {
    $core = 6;
  }
  $LIB = API_LIB . $core;
  if (args('api-lib')) {
    $LIB = args('api-lib');
  }
  if (!is_dir($LIB)) {
    return array('Diretory does not exist.');
  }
  echo 'LIB: ' . $LIB . "\n";
  if (!$handle = opendir($LIB)) {
    $hooks = array();
    return $hooks;
  }
  while (false !== ($file = readdir($handle))) {
      $file = file_get_contents($LIB . '/' . $file);
      if (!preg_match_all('/function hook_([^\(\s]+)\(([^\)]*)\)/mi', $file, $matches)) {
        continue;
      }
      foreach ($matches[1] as $idx => $hook) {
        $hooks[$hook] = $matches[2][$idx];
      }
  }
  closedir($handle);
  return $hooks;
}

/**
 *  Tab completetion for hooks
 */
function drupal_module_builder_hook_tab_completetion($search_str) {
  if (empty($search_str)) {
    return array_keys(get_hooks());
  }
  $matches = array();
  foreach (array_keys(get_hooks()) as $hook) {
    if (strpos($hook, $search_str) !== FALSE) {
      $matches[] = $hook;
    }
  }
  if (empty($matches)) {
    return array($search_str);
  }
  return $matches;
}

/**
 * Helper function to parse strings to arrays
 */
function _string_to_array($str) {
  $array = explode(' ', $str);
  foreach ($array as &$chunk) {
    $chunk = trim($chunk);
    $chunk = strtr($chunk, array(',' => ''));
    if (empty($chunk)) {
      unset($chunk);
    }
  }
  return $array;
}

/**
 * Build information about the new mdoule
 */
function get_module_info() {
  $info = array(
    'name' => require_answer("What is the title of your module?: "),
    'description' => ask_question("Write a summary of what your module does: "),
    'package' => require_answer("What package is your module apart of? Use 'Other' if your unsure: "),
    'dependencies' => ask_question("Please list any dependencies seperated by a space e.g menu taxonomy views: "),
  );
  if (!empty($info['dependencies'])) {
    $info['dependencies'] = _string_to_array($info['dependencies']);
  }
  return $info;
}

/**
 * Get Drupal Hooks user wishes to implement.
 */
function get_implemented_hooks() {
  readline_completion_function('drupal_module_builder_hook_tab_completetion');
  $hooks = readline("Please add any hooks you want to implement, you can add more later. Seperate them with spaces: ");
  if (empty($hooks)) {
    return array();
  }
  $hooks = _string_to_array($hooks);
  return $hooks;
}

/**
 * Get the location of the where to place the module.
 */
function get_module_location() {
  $root = exec('pwd');
  $location = ask_question("Where do you want to place this Module? [$root] ");
  if (empty($location)) {
    $location = $root;
  }
  if (!is_dir($location) && !mkdir($location)) {
    echo "Cannot create module in $location. Permission Denied.\n";
    return get_module_location();
  }
  return $location;
}

/**
 * Build the Module.
 */
function build_module() {
  // Create the module folder
  $name = require_answer("What is the machine name of your module?: ");
  $dir = get_module_location() . "/$name";
  if (!is_dir($dir) && !mkdir($dir)) {
    die("Cannot create module $name because $dir already exists or you do not have the permission to create the directory.\n");
  }
  
  // Create the .info file
  $info = '';
  foreach (get_module_info() as $key => $value) {
    if (is_array($value)) {
      foreach ($value as $val) {
        $info .= "{$key}[] = $val" . PHP_EOL;
      }
    }
    else {
      $info .= "$key = $value" . PHP_EOL;
    }
  }
  $info .= 'core = ' . CORE . PHP_EOL;
  $info .= 'version = ' . CORE . '-1.x-dev' . PHP_EOL;
  file_put_contents($dir . "/$name.info", $info);
  
  //Create .module and .install files
  $hooks = get_hooks();
  foreach (get_implemented_hooks() as $hook) {
    $file = in_array($hook, array('install', 'uninstall', 'schema', 'requirements')) ? 'install' : 'module';
    $function  = PHP_EOL;
    $function .= '/**' . PHP_EOL;
    $function .= ' * Implementation of hook_' . $hook . PHP_EOL;
    $function .= ' */' . PHP_EOL;
    $args = isset($hooks[$hook]) ? $hooks[$hook] : '';
    $function .= "function {$name}_{$hook} ($args) {" . PHP_EOL . PHP_EOL;
    $function .= '}' . PHP_EOL;
    if (!file_exists("$dir/$name.$file")) {
      file_put_contents("$dir/$name.$file", '<?php ' . PHP_EOL);
    }
    file_put_contents("$dir/$name.$file", $function, FILE_APPEND | LOCK_EX);
  }
  echo "Module '$name' created in $dir.\n";
}

if (args('help')) help();


build_module();


